name: Deprecated Build and Release (unused)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use CI and Release workflows instead."
